openapi: 3.0.0
info:
  title: House Tricks
  version: '1.0'
  contact:
    name: Lance Cooper
    email: lance@developersinstitute.co.nz
  description: Manage properties that are listed on the House Tricks application
servers:
  - url: 'http://localhost:5001'
    description: Development
paths:
  /properties:
    parameters: []
    get:
      summary: Retrieve all properties
      tags: []
      responses:
        '200':
          description: Properties found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Property'
              examples:
                example:
                  value:
                    - id: 616552ac49a895b7c0587ece
                      description: 'An easy living, conveniently located, brick & tile home on a highly desirable street and surrounded by quality homes.'
                      address: 123 fake street
                      title: Another Different title
                      img: 'https://placeimg.com/640/480/arch'
                      askingPrice: 891822.26
                      createdBy: auth0|myUserSub
      operationId: get-properties
      description: Retrieves a list of properties
    post:
      summary: Create property
      operationId: post-properties
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'
              examples:
                Property example:
                  value:
                    id: 616552ac49a895b7c0587ece
                    description: 'An easy living, conveniently located, brick & tile home on a highly desirable street and surrounded by quality homes.'
                    address: 123 fake street
                    title: Another Different title
                    img: 'https://placeimg.com/640/480/arch'
                    askingPrice: 891822.26
                    createdBy: auth0|myUserSub
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
                x-examples:
                  example-1:
                    message: Unauthorized
              examples:
                unauthorized:
                  value:
                    message: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                description:
                  type: string
                  minLength: 1
                address:
                  type: string
                  minLength: 1
                title:
                  type: string
                  minLength: 1
                img:
                  type: string
                  minLength: 1
                askingPrice:
                  type: number
              required:
                - description
                - address
                - title
                - img
                - askingPrice
              x-examples:
                example-1:
                  description: 'An easy living, conveniently located, brick & tile home on a highly desirable street and surrounded by quality homes.'
                  address: 123 fake street
                  title: Another Different title
                  img: 'https://placeimg.com/640/480/arch'
                  askingPrice: 891822.26
        description: Create property
      description: Create a new property
      parameters: []
      security:
        - Auth0 JWT: []
components:
  schemas:
    Property:
      description: ''
      type: object
      x-examples:
        Property example:
          id: 616552ac49a895b7c0587ece
          description: 'An easy living, conveniently located, brick & tile home on a highly desirable street and surrounded by quality homes.'
          address: 123 fake street
          title: Another Different title
          img: 'https://placeimg.com/640/480/arch'
          askingPrice: 891822.26
          createdBy: auth0|myUserSub
      title: ''
      properties:
        id:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        address:
          type: string
          minLength: 1
        title:
          type: string
          minLength: 1
        img:
          type: string
          minLength: 1
        createdBy:
          type: string
          minLength: 1
        askingPrice:
          type: number
      required:
        - id
        - description
        - address
        - title
        - img
        - createdBy
        - askingPrice
  securitySchemes:
    Auth0 JWT:
      type: http
      scheme: bearer
